"""empty message

Revision ID: 09727829e6ff
Revises: 071954596955
Create Date: 2023-12-15 00:02:45.815125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09727829e6ff'
down_revision = '071954596955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
